//
import { FragmentType, TestScene } from '~/components/gameModes/testMode/testJsonData'

const { sext, terts, grSec, klSec } = {
  sext: { fragment_1: 'sextstijgend', fragment_2: 'gelijk', fragment_3: 'sextdalend' },
  terts: { fragment_1: 'tertsstijgend', fragment_2: 'gelijk', fragment_3: 'tertsdalend' },
  grSec: { fragment_1: 'gr.sec.stijgend', fragment_2: 'gelijk', fragment_3: 'gr.sec.dalend' },
  klSec: { fragment_1: 'kl.sec.stijgend', fragment_2: 'gelijk', fragment_3: 'kl.sec.dalend' },
}

type Note = 'C' | 'C#' | 'D' | 'D#' | 'E' | 'F' | 'F#' | 'G' | 'G#' | 'A' | 'A#' | 'B'
const notes: Note[] = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']

const distances: Record<FragmentType, number> = {
  gelijk: 0,
  'kl.sec.stijgend': 0,
  'gr.sec.stijgend': 0,
  tertsstijgend: 0,
  sextstijgend: 0,
  'kl.sec.dalend': 1,
  'gr.sec.dalend': 2,
  tertsdalend: 5,
  sextdalend: 10,
}

// functie waarin ik de juiste grondtoon krijg en de juiste fragmenten

const test3DataGrondtonen: TestScene[] = [
  {
    scene: 1,
    grondtoon: 'C',
    octaaf: 3,
    afspelen: 'sextstijgend',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 2,
    grondtoon: 'C',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 3,
    grondtoon: 'C',
    octaaf: 3,
    afspelen: 'tertsstijgend',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 4,
    grondtoon: 'C',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 5,
    grondtoon: 'C',
    octaaf: 3,
    afspelen: 'gr.sec.stijgend',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 6,
    grondtoon: 'C',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 7,
    grondtoon: 'C',
    octaaf: 3,
    afspelen: 'kl.sec.stijgend',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 8,
    grondtoon: 'C',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 9,
    grondtoon: 'C#',
    octaaf: 3,
    afspelen: 'sextstijgend',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 10,
    grondtoon: 'C#',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 11,
    grondtoon: 'C#',
    octaaf: 3,
    afspelen: 'kl.sec.dalend',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 12,
    grondtoon: 'C#',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 13,
    grondtoon: 'D',
    octaaf: 3,
    afspelen: 'sextstijgend',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 14,
    grondtoon: 'D',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 15,
    grondtoon: 'D',
    octaaf: 3,
    afspelen: 'tertsstijgend',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 16,
    grondtoon: 'D',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 17,
    grondtoon: 'D',
    octaaf: 3,
    afspelen: 'gr.sec.dalend',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 18,
    grondtoon: 'D',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 19,
    grondtoon: 'D#',
    octaaf: 3,
    afspelen: 'sextstijgend',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 20,
    grondtoon: 'D#',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 21,
    grondtoon: 'D#',
    octaaf: 3,
    afspelen: 'gr.sec.stijgend',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 22,
    grondtoon: 'D#',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 23,
    grondtoon: 'D#',
    octaaf: 3,
    afspelen: 'kl.sec.stijgend',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 24,
    grondtoon: 'D#',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 25,
    grondtoon: 'E',
    octaaf: 3,
    afspelen: 'tertsdalend',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 26,
    grondtoon: 'E',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 27,
    grondtoon: 'E',
    octaaf: 3,
    afspelen: 'tertsstijgend',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 28,
    grondtoon: 'E',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 29,
    grondtoon: 'E',
    octaaf: 3,
    afspelen: 'kl.sec.dalend',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 30,
    grondtoon: 'E',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 31,
    grondtoon: 'F',
    octaaf: 3,
    afspelen: 'gr.sec.dalend',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 32,
    grondtoon: 'F',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 33,
    grondtoon: 'F#',
    octaaf: 3,
    afspelen: 'tertsdalend',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 34,
    grondtoon: 'F#',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 35,
    grondtoon: 'F#',
    octaaf: 3,
    afspelen: 'gr.sec.stijgend',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 36,
    grondtoon: 'F#',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 37,
    grondtoon: 'F#',
    octaaf: 3,
    afspelen: 'kl.sec.stijgend',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 38,
    grondtoon: 'F#',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 39,
    grondtoon: 'G',
    octaaf: 3,
    afspelen: 'tertsstijgend',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 40,
    grondtoon: 'G',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 41,
    grondtoon: 'G',
    octaaf: 3,
    afspelen: 'kl.sec.dalend',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 42,
    grondtoon: 'G',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 43,
    grondtoon: 'G#',
    octaaf: 3,
    afspelen: 'tertsdalend',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 44,
    grondtoon: 'G#',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 45,
    grondtoon: 'G#',
    octaaf: 3,
    afspelen: 'gr.sec.dalend',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 46,
    grondtoon: 'G#',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 47,
    grondtoon: 'A',
    octaaf: 3,
    afspelen: 'sextdalend',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 48,
    grondtoon: 'A',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 49,
    grondtoon: 'A',
    octaaf: 3,
    afspelen: 'gr.sec.stijgend',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 50,
    grondtoon: 'A',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 51,
    grondtoon: 'A',
    octaaf: 3,
    afspelen: 'kl.sec.stijgend',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 52,
    grondtoon: 'A',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 53,
    grondtoon: 'A#',
    octaaf: 3,
    afspelen: 'sextdalend',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 54,
    grondtoon: 'A#',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 55,
    grondtoon: 'A#',
    octaaf: 3,
    afspelen: 'kl.sec.dalend',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 56,
    grondtoon: 'A#',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 57,
    grondtoon: 'B',
    octaaf: 3,
    afspelen: 'sextdalend',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 58,
    grondtoon: 'B',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 59,
    grondtoon: 'B',
    octaaf: 3,
    afspelen: 'tertsdalend',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 60,
    grondtoon: 'B',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 61,
    grondtoon: 'B',
    octaaf: 3,
    afspelen: 'gr.sec.dalend',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 62,
    grondtoon: 'B',
    octaaf: 3,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 63,
    grondtoon: 'C',
    octaaf: 4,
    afspelen: 'sextstijgend',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 64,
    grondtoon: 'C',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 65,
    grondtoon: 'C',
    octaaf: 4,
    afspelen: 'sextdalend',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 66,
    grondtoon: 'C',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 67,
    grondtoon: 'C',
    octaaf: 4,
    afspelen: 'tertsstijgend',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 68,
    grondtoon: 'C',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 69,
    grondtoon: 'C',
    octaaf: 4,
    afspelen: 'gr.sec.stijgend',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 70,
    grondtoon: 'C',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 71,
    grondtoon: 'C',
    octaaf: 4,
    afspelen: 'kl.sec.stijgend',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 72,
    grondtoon: 'C',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 73,
    grondtoon: 'C#',
    octaaf: 4,
    afspelen: 'sextstijgend',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 74,
    grondtoon: 'C#',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 75,
    grondtoon: 'C#',
    octaaf: 4,
    afspelen: 'kl.sec.dalend',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 76,
    grondtoon: 'C#',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 77,
    grondtoon: 'D',
    octaaf: 4,
    afspelen: 'sextstijgend',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 78,
    grondtoon: 'D',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 79,
    grondtoon: 'D',
    octaaf: 4,
    afspelen: 'tertsstijgend',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 80,
    grondtoon: 'D',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 81,
    grondtoon: 'D',
    octaaf: 4,
    afspelen: 'gr.sec.dalend',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 82,
    grondtoon: 'D',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 83,
    grondtoon: 'D#',
    octaaf: 4,
    afspelen: 'sextstijgend',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 84,
    grondtoon: 'D#',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 85,
    grondtoon: 'D#',
    octaaf: 4,
    afspelen: 'gr.sec.stijgend',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 86,
    grondtoon: 'D#',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 87,
    grondtoon: 'D#',
    octaaf: 4,
    afspelen: 'kl.sec.stijgend',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 88,
    grondtoon: 'D#',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 89,
    grondtoon: 'E',
    octaaf: 4,
    afspelen: 'tertsdalend',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 90,
    grondtoon: 'E',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 91,
    grondtoon: 'E',
    octaaf: 4,
    afspelen: 'tertsstijgend',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 92,
    grondtoon: 'E',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 93,
    grondtoon: 'E',
    octaaf: 4,
    afspelen: 'kl.sec.dalend',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 94,
    grondtoon: 'E',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 95,
    grondtoon: 'F',
    octaaf: 4,
    afspelen: 'gr.sec.dalend',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 96,
    grondtoon: 'F',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 97,
    grondtoon: 'F#',
    octaaf: 4,
    afspelen: 'tertsdalend',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 98,
    grondtoon: 'F#',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 99,
    grondtoon: 'F#',
    octaaf: 4,
    afspelen: 'gr.sec.stijgend',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 100,
    grondtoon: 'F#',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 101,
    grondtoon: 'F#',
    octaaf: 4,
    afspelen: 'kl.sec.stijgend',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 102,
    grondtoon: 'F#',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 103,
    grondtoon: 'G',
    octaaf: 4,
    afspelen: 'tertsstijgend',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 104,
    grondtoon: 'G',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 105,
    grondtoon: 'G',
    octaaf: 4,
    afspelen: 'kl.sec.dalend',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 106,
    grondtoon: 'G',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 107,
    grondtoon: 'G#',
    octaaf: 4,
    afspelen: 'tertsdalend',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 108,
    grondtoon: 'G#',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 109,
    grondtoon: 'G#',
    octaaf: 4,
    afspelen: 'gr.sec.dalend',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 110,
    grondtoon: 'G#',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 111,
    grondtoon: 'A',
    octaaf: 4,
    afspelen: 'sextdalend',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 112,
    grondtoon: 'A',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 113,
    grondtoon: 'A',
    octaaf: 4,
    afspelen: 'gr.sec.stijgend',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 114,
    grondtoon: 'A',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 115,
    grondtoon: 'A',
    octaaf: 4,
    afspelen: 'kl.sec.stijgend',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 116,
    grondtoon: 'A',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 117,
    grondtoon: 'A#',
    octaaf: 4,
    afspelen: 'sextdalend',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 118,
    grondtoon: 'A#',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 119,
    grondtoon: 'A#',
    octaaf: 4,
    afspelen: 'kl.sec.dalend',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 120,
    grondtoon: 'A#',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 121,
    grondtoon: 'B',
    octaaf: 4,
    afspelen: 'sextdalend',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 122,
    grondtoon: 'B',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 123,
    grondtoon: 'B',
    octaaf: 4,
    afspelen: 'tertsdalend',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 124,
    grondtoon: 'B',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 125,
    grondtoon: 'B',
    octaaf: 4,
    afspelen: 'gr.sec.dalend',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 126,
    grondtoon: 'B',
    octaaf: 4,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 127,
    grondtoon: 'C',
    octaaf: 5,
    afspelen: 'sextstijgend',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 128,
    grondtoon: 'C',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 129,
    grondtoon: 'C',
    octaaf: 5,
    afspelen: 'sextdalend',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 130,
    grondtoon: 'C',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 131,
    grondtoon: 'C',
    octaaf: 5,
    afspelen: 'tertsstijgend',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 132,
    grondtoon: 'C',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 133,
    grondtoon: 'C',
    octaaf: 5,
    afspelen: 'gr.sec.stijgend',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 134,
    grondtoon: 'C',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 135,
    grondtoon: 'C',
    octaaf: 5,
    afspelen: 'kl.sec.stijgend',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 136,
    grondtoon: 'C',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 137,
    grondtoon: 'C#',
    octaaf: 5,
    afspelen: 'sextstijgend',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 138,
    grondtoon: 'C#',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 139,
    grondtoon: 'C#',
    octaaf: 5,
    afspelen: 'kl.sec.dalend',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 140,
    grondtoon: 'C#',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 141,
    grondtoon: 'D',
    octaaf: 5,
    afspelen: 'sextstijgend',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 142,
    grondtoon: 'D',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 143,
    grondtoon: 'D',
    octaaf: 5,
    afspelen: 'tertsstijgend',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 144,
    grondtoon: 'D',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 145,
    grondtoon: 'D',
    octaaf: 5,
    afspelen: 'gr.sec.dalend',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 146,
    grondtoon: 'D',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 147,
    grondtoon: 'D#',
    octaaf: 5,
    afspelen: 'sextstijgend',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 148,
    grondtoon: 'D#',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'sextstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 149,
    grondtoon: 'D#',
    octaaf: 5,
    afspelen: 'gr.sec.stijgend',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 150,
    grondtoon: 'D#',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 151,
    grondtoon: 'D#',
    octaaf: 5,
    afspelen: 'kl.sec.stijgend',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 152,
    grondtoon: 'D#',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 153,
    grondtoon: 'E',
    octaaf: 5,
    afspelen: 'tertsdalend',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 154,
    grondtoon: 'E',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 155,
    grondtoon: 'E',
    octaaf: 5,
    afspelen: 'tertsstijgend',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 156,
    grondtoon: 'E',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 157,
    grondtoon: 'E',
    octaaf: 5,
    afspelen: 'kl.sec.dalend',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 158,
    grondtoon: 'E',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 159,
    grondtoon: 'F',
    octaaf: 5,
    afspelen: 'gr.sec.dalend',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 160,
    grondtoon: 'F',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 161,
    grondtoon: 'F#',
    octaaf: 5,
    afspelen: 'tertsdalend',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 162,
    grondtoon: 'F#',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 163,
    grondtoon: 'F#',
    octaaf: 5,
    afspelen: 'gr.sec.stijgend',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 164,
    grondtoon: 'F#',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 165,
    grondtoon: 'F#',
    octaaf: 5,
    afspelen: 'kl.sec.stijgend',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 166,
    grondtoon: 'F#',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 167,
    grondtoon: 'G',
    octaaf: 5,
    afspelen: 'tertsstijgend',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 168,
    grondtoon: 'G',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'tertsstijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 169,
    grondtoon: 'G',
    octaaf: 5,
    afspelen: 'kl.sec.dalend',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 170,
    grondtoon: 'G',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 171,
    grondtoon: 'G#',
    octaaf: 5,
    afspelen: 'tertsdalend',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 172,
    grondtoon: 'G#',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 173,
    grondtoon: 'G#',
    octaaf: 5,
    afspelen: 'gr.sec.dalend',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 174,
    grondtoon: 'G#',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 175,
    grondtoon: 'A',
    octaaf: 5,
    afspelen: 'sextdalend',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 176,
    grondtoon: 'A',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 177,
    grondtoon: 'A',
    octaaf: 5,
    afspelen: 'gr.sec.stijgend',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 178,
    grondtoon: 'A',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 179,
    grondtoon: 'A',
    octaaf: 5,
    afspelen: 'kl.sec.stijgend',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 180,
    grondtoon: 'A',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.stijgend',
    fragment_2: 'gelijk',
  },
  {
    scene: 181,
    grondtoon: 'A#',
    octaaf: 5,
    afspelen: 'sextdalend',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 182,
    grondtoon: 'A#',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 183,
    grondtoon: 'A#',
    octaaf: 5,
    afspelen: 'kl.sec.dalend',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 184,
    grondtoon: 'A#',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'kl.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 185,
    grondtoon: 'B',
    octaaf: 5,
    afspelen: 'sextdalend',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 186,
    grondtoon: 'B',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 187,
    grondtoon: 'B',
    octaaf: 5,
    afspelen: 'tertsdalend',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 188,
    grondtoon: 'B',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'tertsdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 189,
    grondtoon: 'B',
    octaaf: 5,
    afspelen: 'gr.sec.dalend',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 190,
    grondtoon: 'B',
    octaaf: 5,
    afspelen: 'gelijk',
    fragment_1: 'gr.sec.dalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 191,
    grondtoon: 'C',
    octaaf: 6,
    afspelen: 'sextdalend',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
  {
    scene: 192,
    grondtoon: 'C',
    octaaf: 6,
    afspelen: 'gelijk',
    fragment_1: 'sextdalend',
    fragment_2: 'gelijk',
  },
]

const test3data = test3DataGrondtonen.map((scene) => {
  if (scene.afspelen.includes('dalend')) {
    // opnieuw berekenen noot
    const noteIndex = notes.findIndex((x) => x === scene.grondtoon)

    const index = (noteIndex + distances[scene.afspelen]) % notes.length
    const octaafIncrement = (noteIndex + distances[scene.afspelen]) / notes.length > 1 ? 1 : 0
    const newScene = {
      ...scene,
      octaaf: scene.octaaf + octaafIncrement,
      grondtoon: notes[index]!,
    }
    return newScene
  }

  return scene
})
export { test3data }
