import { GetStaticProps, type NextPage } from "next";
import Head from "next/head";
import Sublevel from "~/components/subLevel";
import { generateServerSideHelper } from "~/server/helpers/serverSideHelper";
import { api } from "~/utils/api";

const SublevelsPage: NextPage<{ levelId: string }> = ({ levelId }) => {
    const subLevelsOfLevel = api.level.getSubLevelsOfLevel.useQuery({ levelId });
    console.log("data: " + subLevelsOfLevel.data)
    return (<>
        <Head>
            <title>Voortgang Musi-CI</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex grow flex-col items-center justify-center bg-gray-900">
            <div className="container mx-auto flex flex-col items-center justify-center space-y-8 rounded-2xl border-4 border-white">
                {/* Title */ }
                <h1 className="w-full border-b-2 py-2 text-center text-3xl font-extrabold tracking-tight text-white ">
                    Sublevels
                </h1>
                <div className=" flex w-full flex-col justify-between space-y-8 pl-8">
                    { subLevelsOfLevel.data?.map((subLevel) => (
                        <Sublevel key={ subLevel.id } sublevelId={ subLevel.id } levelId={levelId} name={ subLevel.name } borderColor="green" />
                    )) }
                </div>
            </div>
        </main>
    </>);
};

export const getStaticProps: GetStaticProps = async (context) => {
    const ssg = generateServerSideHelper();
    const levelId = context.params?.levelId;

    if (typeof levelId !== "string") throw new Error("No levelId");

    // await ssg.   Do the prefetch of the level data here
    return {
        props: {
            trpcState: ssg.dehydrate(),
            levelId: levelId,
        },
    };
};

export const getStaticPaths = () => {
    return { paths: [], fallback: "blocking" };
};

export default SublevelsPage;
