import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Welcome: NextPage = () => {
  return (<>
    <Head>
      <title>Welcome to T3</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <div className="container mx-auto flex flex-col items-center justify-center rounded-t-md border-black">
        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          Welcome!
        </h1>
        <Link
          className="my-5 flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
          href="https://create.t3.gg/en/usage/first-steps"
          target="_blank"
        >
          <h3 className="text-2xl font-bold">Aan de slag</h3>
        </Link>
      </div>
    </main>
  </>)
};

export default Welcome;
