import { GetServerSidePropsContext } from 'next'
import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect } from 'react'
import { LoadingPage } from '~/components/loading'
import { Button } from '~/components/ui/button'
import { useUserActivity } from '~/hooks/useUserActivity'
import { getSSRAuth } from '~/utils/authUtils'

const LoginPage = () => {
  const { data: session } = useSession()
  const { logSignOutActivity } = useUserActivity()

  function getLoginText() {
    if (!session?.user.id) {
      return 'Log hier in om te starten'
    } else {
      return 'Druk hieronder om uit te loggen'
    }
  }

  async function handleSignOut() {
    await logSignOutActivity()
    await signOut({ redirect: false, callbackUrl: '/login' })
  }

  useEffect(() => {
    if(!session){
      signIn('credentials', { redirect: true, callbackUrl: '/tutorial' })
    }
  }, [session])

  if(!session) return <LoadingPage />

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex grow flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-4 px-4 py-16 ">
          <h2 className=" font-heading text-center text-5xl tracking-tight">Musi-CI Melody Game</h2>
          <h2 className="md: text-center text-2xl leading-normal tracking-tight text-muted-foreground md:text-3xl">
            Trainen met verschillen tussen toonhoogtes en korte melodietjes
          </h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8"></div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-xl">{getLoginText()}</p>
            <div className="flex flex-col gap-5">
              <Button
                size={'lg'}
                onClick={
                  session
                    ? () => handleSignOut()
                    : () => void signIn('credentials', { redirect: true, callbackUrl: '/tutorial' })
                }
              >
                {session ? 'Uitloggen' : 'Inloggen'}
              </Button>
              {session?.user.id && (
                <Button size={'lg'} asChild>
                  <Link href={'/podium'}> Ga naar volgende pagina</Link>
                </Button>
              )}
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default LoginPage

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  return await getSSRAuth(ctx)
}
