import { type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { signIn, signOut, useSession } from 'next-auth/react'
import { Button } from '~/components/ui/button'
import { useRouter } from 'next/router'

const LoginPage: NextPage = () => {
  const { data: sessionData } = useSession()

  function getLoginText() {
    if (!sessionData?.user) {
      return 'Log hier in om te starten'
    } else {
      return 'Druk hieronder om uit te loggen'
    }
  }

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex grow flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-4 px-4 py-16 ">
          <h2 className=" font-heading text-center text-5xl tracking-tight">Musi-CI Melody Game</h2>
          <h2 className="text-2xl md: text-center md:text-3xl leading-normal tracking-tight text-muted-foreground">
            Trainen met verschillen tussen toonhoogtes en korte melodietjes
          </h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8"></div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-xl">{getLoginText()}</p>
            <div className="flex gap-5">
              <Button
                size={'lg'}
                onClick={
                  sessionData
                    ? () => void signOut()
                    : () =>
                        void signIn(undefined, { callbackUrl: 'http://localhost:3000/tutorial' })
                }
              >
                {sessionData ? 'Uitloggen' : 'Inloggen'}
              </Button>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default LoginPage
