import { type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { signIn, signOut, useSession } from 'next-auth/react'
import { Button } from '~/components/ui/button'

const LoginPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex grow flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-4 px-4 py-16 ">
          <h2 className=" font-heading text-3xl tracking-tight sm:text-[5rem]">
            Musi-CI Melody Game
          </h2>
          <h2 className="text-3xl leading-normal tracking-tight text-muted-foreground">
            Trainen met verschillen tussen toonhoogtes en korte melodietjes
          </h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8"></div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl">Log hier in om te starten</p>
            <div className="flex gap-5">
              <AuthProvider />
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default LoginPage

const AuthProvider: React.FC = () => {
  const { data: sessionData } = useSession()

  return (
    <Button
      size={'lg'}
      onClick={
        sessionData
          ? () => void signOut()
          : () => void signIn(undefined, { callbackUrl: 'http://localhost:3000/tutorial' })
      }
    >
      {sessionData ? 'Uitloggen' : 'Inloggen'}
    </Button>
  )
}
