import { GetStaticProps, type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { buttonVariants } from "~/components/ui/button";
import { cn } from "~/lib/utils";
import { generateServerSideHelper } from "~/server/helpers/serverSideHelper";
import { api } from "~/utils/api";

const UserLevelsPage: NextPage<{ gameId: string }> = ({ gameId }) => {
    const { data: sessiondata } = useSession();
    const levelsOfGameQuery = api.game.getLevelsOfGame.useQuery({ gameId: parseInt(gameId) })

    return (
        <>
            <Head>
                <title>Levels</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="flex grow flex-col items-center justify-center">
                <div className="container mx-auto flex flex-col items-center justify-center space-y-8 rounded-2xl border-4 border-primary">
                    <h2 className="w-full border-b-2 py-2 text-center text-3xl font-extrabold tracking-tight">
                        Voortgang Musi-CI Levels
                    </h2>
                    <div className=" flex w-full flex-col justify-between space-y-8 py-4 pl-8">
                        { levelsOfGameQuery.data?.map((level) => (
                            <Link key={ level.id }
                                className={ cn(buttonVariants({ size: "lg" }), 'h-20 rounded-xl') }
                                href={ `/progress/level/${level.id}` }
                            >
                                <div className="flex w-full items-center justify-between">
                                    <div className="flex justify-start space-x-4">
                                        <div className=" flex h-16 w-16 items-center justify-center rounded-lg border-4 text-center text-2xl font-bold" style={ { borderColor: 'green' } }>
                                            { level.id }
                                        </div>
                                        <div className=" flex h-16 w-48 items-center justify-center text-2xl font-medium">
                                            { level.name }
                                        </div>
                                    </div>
                                </div>
                            </Link>
                        )) }
                    </div>
                </div>
            </section>
        </>);
};

export const getStaticProps: GetStaticProps = async (context) => {
    const ssg = generateServerSideHelper();
    const gameId = context.params?.gameId;

    if (typeof gameId !== "string") throw new Error("No gameId");

    await ssg.game.getLevelsOfGame.prefetch({ gameId: parseInt(gameId) })

    return {
        props: {
            trpcState: ssg.dehydrate(),
            gameId,
        },
    };
};

export const getStaticPaths = () => {
    return { paths: [], fallback: "blocking" };
};

export default UserLevelsPage;
