import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Level from "~/components/level";
import { api } from "~/utils/api";

const UserLevelsPage: NextPage = () => {
    const router = useRouter();
    const { gameId } = router.query;

    const levelsOfGameQuery = api.game.getLevelsOfGame.useQuery({ gameId: parseInt(gameId as string) })

    return (<>
        <Head>
            <title>Voortgang Musi-CI</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex grow flex-col items-center justify-center bg-gray-900">
            <div className="container mx-auto flex flex-col items-center justify-center space-y-8 rounded-2xl border-4 border-white">
                {/* Title */ }
                <h1 className="w-full border-b-2 py-2 text-center text-3xl font-extrabold tracking-tight text-white ">
                    Voortgang Musi-CI
                </h1>
                <div className=" flex w-full flex-col justify-between space-y-8 pl-8">
                { levelsOfGameQuery.data?.map((level) => (
                    <Level key={ level.id } number={ level.id } name={ level.name } score={ level.BPM } borderColor="green" />
                )) }
                </div>
            </div>
        </main>
    </>);
};

export default UserLevelsPage;
