import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { buttonVariants } from "~/components/ui/button";
import { cn } from "~/lib/utils";
import { api } from "~/utils/api";

const UserGamesPage: NextPage = () => {
    const { data: session } = useSession();
    const gamesOfUserQuery = api.user.getGamesOfUser.useQuery({ id: session?.user.id })

    return (
        <>
            <Head>
                <title>Games</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="flex grow flex-col items-center justify-center">
                <div className="container mx-auto flex flex-col items-center justify-center space-y-8 rounded-2xl border-4 border-primary">
                    <h2 className="w-full border-b-2 py-2 text-center text-3xl font-extrabold tracking-tight">
                        Voortgang Musi-CI Games
                    </h2>
                    <div className=" flex w-full flex-col justify-between space-y-8 py-4 pl-8">
                        { gamesOfUserQuery.data?.map((game) => (
                            <Link key={ game.id }
                                className={ cn(buttonVariants({ size: "lg" }), 'h-20 rounded-xl') }
                                href={ `/progress/${game.id}` }
                            >
                                <div className="flex w-full items-center justify-between">
                                    <div className="flex justify-start space-x-4">
                                        <div className=" flex h-16 w-16 items-center justify-center rounded-lg border-4 text-center text-2xl font-bold" style={ { borderColor: "green" } }>
                                            { game.id }
                                        </div>
                                        <div className=" flex h-16 w-48 items-center justify-center text-2xl font-medium">
                                            { game.name }
                                        </div>
                                    </div>
                                    <div className=" flex h-16 w-16 items-center justify-center text-2xl font-medium">
                                        { game.description }
                                    </div>
                                </div>
                            </Link>
                        )) }
                    </div>
                </div>
            </section>
        </>
    );
};

export default UserGamesPage;
