import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Game from "~/components/game";
import { api } from "~/utils/api";

const UserGamesPage: NextPage = () => {
    const { data: session } = useSession();
    const gamesOfUserQuery = api.user.getGamesOfUser.useQuery({ id: session?.user.id })

    return (<>
        <Head>
            <title>User games</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex grow flex-col items-center justify-center bg-gray-900">
            <div className="container mx-auto flex flex-col items-center justify-center space-y-8 rounded-2xl border-4 border-white">
                {/* Title */ }
                <h1 className="w-full border-b-2 py-2 text-center text-3xl font-extrabold tracking-tight text-white ">
                    Voortgang Musi-CI Games
                </h1>
                <div className=" flex w-full flex-col justify-between space-y-8 pl-8">
                    { gamesOfUserQuery.data?.map((game) => (
                        <Game key={ game.id } gameId={ game.id } name={ game.name } description={ game.description || "" } borderColor="green" />
                    )) }
                    {/* <Link
                        className="w-full rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 "
                        href="/modeSelect/myLevel"
                    >
                        <Game key={ "5" } number={ 5 } name={ "test" } score={ 999 } borderColor="green" />
                    </Link>
                    <Link
                        className="flex rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 "
                        href="/modeSelect/myLevel"
                    >
                        <Game key={ "5" } number={ 5 } name={ "test" } score={ 999 } borderColor="green" />
                    </Link>
                    <Link
                        className="flex rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 "
                        href="/modeSelect/myLevel"
                    >
                        <Game key={ "5" } number={ 5 } name={ "test" } score={ 999 } borderColor="green" />
                    </Link>
                    <Link
                        className="flex rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 "
                        href="/modeSelect/myLevel"
                    >
                        <Game key={ "5" } number={ 5 } name={ "test" } score={ 999 } borderColor="green" />
                    </Link> */}
                </div>
            </div>
        </main>
    </>);
};

export default UserGamesPage;
