import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Progress: NextPage = () => {
    return (<>
        <Head>
            <title>Voortgang Musi-CI</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
            <div className="container mx-auto flex flex-col items-center justify-center space-y-8 rounded-2xl border-4 border-white">
                {/* Title */ }
                <h1 className="w-full border-b-2 py-2 text-center text-3xl font-extrabold tracking-tight text-white ">
                    Voortgang Musi-CI
                </h1>
                {/* List of available levels */ }
                <div className="flex flex-col items-center justify-between">
                    {/* Place the level component here and fill it with data... */ }
                </div>
                {/* Ga verder button, maar denk ik niet nodig */ }
                <Link
                    className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 "
                    href="/login"
                >
                    <h3 className="text-2xl font-bold">Ga verder</h3>
                </Link>
            </div>
        </main>
    </>)
};

export default Progress;
