import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Level from "~/components/level";

const Progress: NextPage = () => {
    return (<>
        <Head>
            <title>Voortgang Musi-CI</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex grow flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
            <div className="container mx-auto flex flex-col items-center justify-center space-y-8 rounded-2xl border-4 border-white">
                {/* Title */ }
                <h1 className="w-full border-b-2 py-2 text-center text-3xl font-extrabold tracking-tight text-white ">
                    Voortgang Musi-CI
                </h1>
                <div className=" flex w-full flex-col justify-between space-y-8 pl-8">
                    <Link
                        className="flex rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 "
                        href="/modeSelect/myLevel"
                    >
                        <Level key={ "5" } number={ 5 } name={ "test" } score={ 999 } borderColor="green" />
                    </Link>
                    <Link
                        className="w-full rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 "
                        href="/modeSelect/myLevel"
                    >
                        <Level key={ "5" } number={ 5 } name={ "test" } score={ 999 } borderColor="green" />
                    </Link>
                    <Link
                        className="flex rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 "
                        href="/modeSelect/myLevel"
                    >
                        <Level key={ "5" } number={ 5 } name={ "test" } score={ 999 } borderColor="green" />
                    </Link>
                    <Link
                        className="flex rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 "
                        href="/modeSelect/myLevel"
                    >
                        <Level key={ "5" } number={ 5 } name={ "test" } score={ 999 } borderColor="green" />
                    </Link>
                    <Link
                        className="flex rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 "
                        href="/modeSelect/myLevel"
                    >
                        <Level key={ "5" } number={ 5 } name={ "test" } score={ 999 } borderColor="green" />
                    </Link>
                </div>
            </div>
        </main>
    </>);
};

export default Progress;
