import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { Button, buttonVariants } from '~/components/ui/button'
import { cn } from '~/lib/utils'
import { useLuisterenStore } from '~/stores/gameModes/luisterenStore'

interface Props {
  children: React.ReactNode
  title: string
  backPath?: string
  classNameParent?: string
  shouldRenderBackButton?: boolean
  instrumentURL?: string | null
}

const ContentContainer: React.FC<Props> = ({
  children,
  title,
  classNameParent,
  backPath = '/',
  shouldRenderBackButton = true,
  instrumentURL = undefined,
}) => {
  const router = useRouter()
  const { shouldRenderCinieInContentContainer } = useLuisterenStore()

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex grow flex-col items-center justify-center">
        <div className="container mx-auto flex flex-col items-center justify-start gap-6 py-12">
          <div className="w-full rounded-2xl">
            <div className="relative flex w-full justify-start rounded-t-2xl bg-primary-foreground">
              <div className="relative size-40 px-2">
                {shouldRenderCinieInContentContainer && (
                  <Image
                    objectFit="fill"
                    src="/images/cinie-duim.jpg"
                    alt="cinie"
                    className=""
                    sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                    fill
                  />
                )}
              </div>

              <div className="flex w-full items-center justify-start px-36 pb-5">
                <h2 className="text-3xl font-extrabold">{title}</h2>
              </div>

              <div className="relative size-36 px-8">
                {instrumentURL && (
                  <Image
                    objectFit="cover"
                    src={instrumentURL}
                    alt="instrument"
                    className=""
                    sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                    fill
                  />
                )}
              </div>
            </div>
            <div
              className={cn(
                'flex w-full flex-col items-center justify-between',
                classNameParent,
              )}
            >
              {children}
            </div>
          </div>
          {shouldRenderBackButton && (
            <Button
              size={'lg'}
              onClick={() => {
                router.push(backPath)
              }}
            >
              <h3 className="text-xl">Terug</h3>
            </Button>
          )}
        </div>
      </section>
    </>
  )
}

export default ContentContainer
