import Head from 'next/head'
import { useRouter } from 'next/router'
import { Button, buttonVariants } from '~/components/ui/button'
import { cn } from '~/lib/utils'

interface Props {
  children: React.ReactNode
  title: string
  backPath: string
  classNameParent?: string
  shouldRenderBackButton?: boolean
}

const ContentContainer: React.FC<Props> = ({
  children,
  title,
  backPath,
  classNameParent,
  shouldRenderBackButton = true,
}) => {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex grow flex-col items-center justify-center">
        <div className="container mx-auto flex min-h-fit  w-5/6 flex-col items-center justify-start rounded-2xl border-4 border-primary p-0 ">
          <div className="relative flex justify-center w-full border-b-2 border-primary py-4 text-center text-2xl font-extrabold tracking-tight md:text-3xl">
            <h2 className='w-5/6'>{title}</h2>
            <div className="absolute right-3 top-3 rounded-full bg-primary w-12 h-12"/>
          </div>
          <div
            className={cn(
              'mt-8 flex w-full flex-col items-center justify-between gap-8 px-2 pb-8',
              classNameParent,
            )}
          >
            {children}
          </div>
        </div>
        {shouldRenderBackButton && (
          <Button
            onClick={() => {
              router.push(backPath)
            }}
            className={cn(buttonVariants({ size: 'lg' }), 'my-5 h-16 rounded-xl')}
          >
            <h3 className="text-xl">Terug</h3>
          </Button>
        )}
      </section>
    </>
  )
}

export default ContentContainer
